### ISSUE TITLE
Installtion via apt repo times out

### ISSUE THREAD

**Issue by niwoerner** [plengauer/opentelemetry-bash#529]
Hi @plengauer , thanks for the great tool! 

I'm playing around with it right now and noticed that the installation times out when trying to use this apt repo: https://3.73.14.87:8000/ 

For me the connection to the apt repo seems to time out. 

Installing it via wget directly from the github repo works fine :)

**Comment by plengauer** [comment]
I think I know why. The Apt repo is actually just an apt-like facade that HTTP redirects to the deb packages in the releases of this repo to be more unix-native. Therefore its only http and not https because it only ever serves redirects.

I'll verify if that theory, and if correct, ill fix the readme and change https to http, and probably also add a note to that effect.

**Comment by plengauer** [comment]
I confirmed that using http works for me, and that using the https url causes the same behavior you describe. Thanks for reporting!

**Comment by niwoerner** [comment]
Thank you for the quick response and correction!
